import { Title } from "./types";

export const STUB_MOVIES: Title[] = [
  {
    id: "movie-1",
    tmdbId: 533535,
    type: "movie",
    title: "Deadpool & Wolverine",
    overview: "Deadpool and Wolverine team up for a mind-bending, multiversal adventure.",
    posterPath: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdropPath: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    releaseDate: "2024-07-26",
    genres: ["Action", "Comedy", "Superhero"],
    rating: 7.7,
    voteCount: 8200,
    language: "en",
    year: 2024,
    streamingPlatforms: ["Disney+"],
  },
  {
    id: "movie-2",
    tmdbId: 945961,
    type: "movie",
    title: "Alien: Romulus",
    overview: "Young space colonizers come face to face with the most terrifying life form in the universe.",
    posterPath: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    backdropPath: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
    releaseDate: "2024-08-16",
    genres: ["Horror", "Science Fiction", "Thriller"],
    rating: 7.3,
    voteCount: 5100,
    language: "en",
    year: 2024,
    streamingPlatforms: ["Hulu"],
  },
  {
    id: "movie-3",
    tmdbId: 1022789,
    type: "movie",
    title: "Inside Out 2",
    overview: "Riley's mind headquarters is now home to new emotions — including Anxiety.",
    posterPath: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    backdropPath: "/xg27NrXi7VXCGUr7MlcbgrYR2Aq.jpg",
    releaseDate: "2024-06-14",
    genres: ["Animation", "Family", "Comedy"],
    rating: 7.6,
    voteCount: 7800,
    language: "en",
    year: 2024,
    streamingPlatforms: ["Disney+"],
  },
  {
    id: "movie-4",
    tmdbId: 519182,
    type: "movie",
    title: "Despicable Me 4",
    overview: "Gru meets his most formidable nemesis yet — a criminal named Maxime Le Mal.",
    posterPath: "/wWba3TaojhK7NdycyUPlLtN0LtR.jpg",
    backdropPath: "/lgkgOffsrEOSRqNONGMPrqhMHFzZ.jpg",
    releaseDate: "2024-07-03",
    genres: ["Animation", "Comedy", "Family"],
    rating: 7.1,
    voteCount: 4300,
    language: "en",
    year: 2024,
    streamingPlatforms: ["Netflix"],
  },
  {
    id: "movie-5",
    tmdbId: 748783,
    type: "movie",
    title: "The Garfield Movie",
    overview: "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure.",
    posterPath: "/xYduFGuch9OwbCOEUiNHEMqGJlZa.jpg",
    backdropPath: "/gKgEIJgVp68LlGmk9FqtXbRKx4J.jpg",
    releaseDate: "2024-05-24",
    genres: ["Animation", "Comedy", "Family"],
    rating: 6.8,
    voteCount: 2900,
    language: "en",
    year: 2024,
    streamingPlatforms: ["Netflix"],
  },
  {
    id: "movie-6",
    tmdbId: 438631,
    type: "movie",
    title: "Dune: Part Two",
    overview: "Paul Atreides unites with Chani and the Fremen as he seeks revenge against the conspirators who destroyed his family.",
    posterPath: "/czembW0Rk1Ke7lCJGahbOhdCuhV.jpg",
    backdropPath: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    releaseDate: "2024-03-01",
    genres: ["Science Fiction", "Adventure", "Drama"],
    rating: 8.4,
    voteCount: 9200,
    language: "en",
    year: 2024,
    streamingPlatforms: ["Max"],
  },
  {
    id: "movie-7",
    tmdbId: 695721,
    type: "movie",
    title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    overview: "64 years before he becomes the tyrannical President Snow, Coriolanus Snow competes in the 10th Hunger Games.",
    posterPath: "/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg",
    backdropPath: "/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
    releaseDate: "2023-11-17",
    genres: ["Action", "Adventure", "Science Fiction"],
    rating: 7.2,
    voteCount: 6100,
    language: "en",
    year: 2023,
    streamingPlatforms: ["Peacock"],
  },
  {
    id: "movie-8",
    tmdbId: 569094,
    type: "movie",
    title: "Spider-Man: Across the Spider-Verse",
    overview: "Miles Morales catapults across the multiverse, where he encounters a team of Spider-People.",
    posterPath: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdropPath: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    releaseDate: "2023-06-02",
    genres: ["Animation", "Action", "Adventure"],
    rating: 8.7,
    voteCount: 11000,
    language: "en",
    year: 2023,
    streamingPlatforms: ["Netflix"],
  },
];

export const STUB_ANIME: Title[] = [
  {
    id: "anime-1",
    anilistId: 21,
    type: "anime",
    title: "One Piece",
    overview: "Monkey D. Luffy sets off on an adventure to find the legendary One Piece treasure and become King of the Pirates.",
    posterPath: "/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    rating: 8.9,
    voteCount: 42000,
    language: "ja",
    studio: "Toei Animation",
    episodeCount: 1100,
    streamingPlatforms: ["Crunchyroll", "Netflix"],
    nextAirDate: "2026-04-06",
  },
  {
    id: "anime-2",
    anilistId: 101922,
    type: "anime",
    title: "Demon Slayer: Kimetsu no Yaiba",
    overview: "Tanjiro Kamado becomes a demon slayer to avenge his family and cure his sister Nezuko.",
    posterPath: "/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
    genres: ["Action", "Fantasy", "Drama"],
    rating: 8.7,
    voteCount: 38000,
    language: "ja",
    studio: "ufotable",
    streamingPlatforms: ["Crunchyroll", "Netflix"],
  },
  {
    id: "anime-3",
    anilistId: 16498,
    type: "anime",
    title: "Attack on Titan",
    overview: "In a world where humanity hides behind walls from monstrous giants, Eren Yeager vows to fight back.",
    posterPath: "/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
    genres: ["Action", "Drama", "Fantasy", "Horror"],
    rating: 9.1,
    voteCount: 45000,
    language: "ja",
    studio: "MAPPA",
    streamingPlatforms: ["Crunchyroll", "Funimation"],
  },
  {
    id: "anime-4",
    anilistId: 11061,
    type: "anime",
    title: "Hunter x Hunter",
    overview: "Gon Freecss discovers that his father, Ging, is a world-famous Hunter and sets out to become one himself.",
    posterPath: "/1ZTsuMCKS4fBLmBiLpZSRMqGdBL.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    rating: 9.0,
    voteCount: 39000,
    language: "ja",
    studio: "Madhouse",
    episodeCount: 148,
    streamingPlatforms: ["Netflix", "Crunchyroll"],
  },
  {
    id: "anime-5",
    anilistId: 20,
    type: "anime",
    title: "Naruto",
    overview: "A young ninja dreams of becoming the greatest ninja in his village while hiding a great secret within.",
    posterPath: "/xppeysfvDKVx775MFuH8Z9BlpMk.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    rating: 8.3,
    voteCount: 36000,
    language: "ja",
    studio: "Pierrot",
    episodeCount: 220,
    streamingPlatforms: ["Netflix", "Crunchyroll"],
  },
  {
    id: "anime-6",
    anilistId: 154587,
    type: "anime",
    title: "Frieren: Beyond Journey's End",
    overview: "An elven mage journeys to the afterlife to reconnect with her departed human companions.",
    posterPath: "/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
    genres: ["Fantasy", "Adventure", "Slice of Life"],
    rating: 9.3,
    voteCount: 28000,
    language: "ja",
    studio: "Madhouse",
    streamingPlatforms: ["Crunchyroll"],
    nextAirDate: "2026-04-01",
  },
  {
    id: "anime-7",
    anilistId: 9253,
    type: "anime",
    title: "Steins;Gate",
    overview: "A group of friends discover they can send messages to the past, changing history with dire consequences.",
    posterPath: "/6tSwCUHWvTrWwIjDjFjCiIfmcuY.jpg",
    genres: ["Science Fiction", "Thriller", "Drama"],
    rating: 9.2,
    voteCount: 31000,
    language: "ja",
    studio: "White Fox",
    episodeCount: 24,
    streamingPlatforms: ["Crunchyroll", "Funimation"],
  },
  {
    id: "anime-8",
    anilistId: 97940,
    type: "anime",
    title: "Made in Abyss",
    overview: "An orphaned girl and a robot boy descend into the Abyss, an enormous pit filled with artifacts and monsters.",
    posterPath: "/dvbMCeFjCYNdxjqOcCnCSEzeFbj.jpg",
    genres: ["Adventure", "Fantasy", "Drama"],
    rating: 8.8,
    voteCount: 22000,
    language: "ja",
    studio: "Kinema Citrus",
    streamingPlatforms: ["Amazon Prime"],
  },
];

export const STUB_TRENDING: Title[] = [
  ...STUB_MOVIES.slice(0, 4),
  ...STUB_ANIME.slice(0, 4),
];

export const ALL_GENRES = [
  "Action", "Adventure", "Animation", "Comedy", "Drama", "Fantasy",
  "Horror", "Mystery", "Romance", "Science Fiction", "Thriller", "Crime",
  "Family", "Superhero", "Slice of Life",
];

export const ALL_LANGUAGES = [
  { code: "en", name: "English" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "fr", name: "French" },
  { code: "es", name: "Spanish" },
];

export const STREAMING_PLATFORMS = [
  "Netflix", "Disney+", "Hulu", "Max", "Amazon Prime", "Crunchyroll", "Funimation", "Peacock",
];
